---
name: 'Command Docker GitHub Action'
description: |
  A simple GitHub Action for running a shell command via a Docker container
author: 'Cliffano Subagio'
branding:
  icon: 'arrow-right-circle'
  color: 'white'
inputs:
  command:
    description: |
      Shell command to be executed via a Docker container
    type: string
    required: true
  image:
    description: |
      Docker image to be used for running the container
    type: string
    required: false
    default: 'alpine:3.20'
  shell:
    description: |
      Shell to be used for running the command
    type: string
    required: false
    default: 'sh'
  env_file:
    description: |
      Path to env file containing environment variables  made available during shell command execution
    type: string
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Build Docker image on the the GitHub Action directory
      shell: sh
      run: |
        cd $GITHUB_ACTION_PATH && docker build -f Dockerfile --build-arg IMAGE=${{ inputs.image }} --build-arg SHELL=${{ inputs.shell }} -t local_image:8.8.8 .
    - name: Deploy on pushes

      run: echo 'DEPLOY=true' >> "$GITHUB_ENV"
    - name: Run Docker container on the GitHub Workspace directory
      if: inputs.env_file == ''
      shell: sh
      run: |
        cd $GITHUB_WORKSPACE && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v .:/opt/workspace/ --name local_container local_image:8.8.8 "${{ inputs.command }}"
    - name: Run Docker container on the GitHub Workspace directory with env file
      if: inputs.env_file != ''
      shell: sh
      run: |
        cd $GITHUB_WORKSPACE && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v .:/opt/workspace/ --env-file "${{ inputs.env_file }}" --name local_container local_image:8.8.8 "${{ inputs.command }}"
