---
name: 'Command Docker GitHub Action'
description: |
  A simple GitHub Action for running a shell command via a Docker container
author: 'Cliffano Subagio'
branding:
  icon: 'arrow-right-circle'
  color: 'white'
inputs:
  command:
    description: |
      Shell command to be executed via a Docker container
    type: string
    required: true
  docker_image:
    description: |
      Docker image to be used for running the container
    type: string
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.docker_image }}
    - ${{ inputs.command }}
