---
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: make ci
      - name: 'Execute cat /etc/*-release using default sh shell via default Docker container'
        uses: cliffano/command-docker-action@main
        with:
          command: 'cat /etc/*-release'
      - name: 'Execute cat /etc/*-release using bash shell via Ubuntu 22.04 Docker container'
        uses: cliffano/command-docker-action@main
        with:
          command: 'cat /etc/*-release'
          image: ubuntu:22.04
          shell: bash
      - name: 'Execute cat /etc/*-release using bash shell via Rocky Linux 9.3 Docker container'
        uses: cliffano/command-docker-action@main
        with:
          command: 'cat /etc/*-release'
          image: rockylinux:9.3
          shell: bash
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'SOME_ENV_VAR'
          value: 'Some value'
          envPath: '/tmp/.env'
      - uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: '/tmp/.env'
        env:
          SOME_ENV_VAR: 'Some value'
      - name: 'Display environment variables'
        uses: cliffano/command-docker-action@main
        with:
          command: 'echo "SOME_ENV_VAR: $SOME_ENV_VAR"'
          env_file: '/tmp/.env'
